In [19]:
import torch
from tqdm import tqdm
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [4]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-42, -53,  72, -46, -22, -12])

In [5]:
t = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
t

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
inp = torch.empty(2,3)
inp

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
ar = torch.arange(5)
ar

tensor([0, 1, 2, 3, 4])

In [13]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [14]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [15]:
# On the main diagonal we have ones and zeros everywhere else
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
%%time
start_time = time.time()
# matrix operations here
zeros =torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00027585
CPU times: user 528 µs, sys: 305 µs, total: 833 µs
Wall time: 637 µs


In [23]:
# Define a probability tensor:
probs = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. Each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution 
samples = torch.multinomial(probs, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 0, 1, 1, 1, 1, 1, 1, 1])


In [27]:
# We will use it for text generation
t = torch.tensor([1,2,3,4])
out = torch.cat((t, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [25]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [26]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])